services:
  eventify:
    build:
      context: .
      dockerfile: ./docker/dev-bun.Dockerfile
    volumes:
      - .:/app/eventify:K
      - /app/eventify/node_modules
    restart: always
    ports:
      - 5173:5173
    # env_file:
    #     - .env
    environment:
      PGHOST: postgres
      PGDATABASE: eventify
      PGUSERNAME: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      # DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-sql/dump_05-03-2025_22_08_28.sql:/docker-entrypoint-initdb.d/init2.sql
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "eventify"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata: {}
