services:
  eventify:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - .:/app/eventify
      - /app/eventify/node_modules
    restart: always
    ports:
      - 5173:5173
    env_file:
        - .env
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "eventify"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata: {}
